/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedMesDevisRouteImport } from './routes/_authenticated/mes-devis'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminDevisRouteImport } from './routes/admin/devis'
import { Route as AdminProduitsRouteImport } from './routes/admin/produits'
import { Route as AdminUtilisateursRouteImport } from './routes/admin/utilisateurs'
import { Route as ProduitsIndexRouteImport } from './routes/produits/index'
import { Route as ProduitsIdRouteImport } from './routes/produits/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedMesDevisRoute = AuthenticatedMesDevisRouteImport.update({
  id: '/mes-devis',
  path: '/mes-devis',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminDevisRoute = AdminDevisRouteImport.update({
  id: '/devis',
  path: '/devis',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminProduitsRoute = AdminProduitsRouteImport.update({
  id: '/produits',
  path: '/produits',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminUtilisateursRoute = AdminUtilisateursRouteImport.update({
  id: '/utilisateurs',
  path: '/utilisateurs',
  getParentRoute: () => AdminRouteRoute,
} as any)
const ProduitsIndexRoute = ProduitsIndexRouteImport.update({
  id: '/produits/',
  path: '/produits/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProduitsIdRoute = ProduitsIdRouteImport.update({
  id: '/produits/$id',
  path: '/produits/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/mes-devis': typeof AuthenticatedMesDevisRoute
  '/admin/devis': typeof AdminDevisRoute
  '/admin/produits': typeof AdminProduitsRoute
  '/admin/utilisateurs': typeof AdminUtilisateursRoute
  '/produits/$id': typeof ProduitsIdRoute
  '/admin/': typeof AdminIndexRoute
  '/produits/': typeof ProduitsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/mes-devis': typeof AuthenticatedMesDevisRoute
  '/admin/devis': typeof AdminDevisRoute
  '/admin/produits': typeof AdminProduitsRoute
  '/admin/utilisateurs': typeof AdminUtilisateursRoute
  '/produits/$id': typeof ProduitsIdRoute
  '/admin': typeof AdminIndexRoute
  '/produits': typeof ProduitsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/admin': typeof AdminRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/mes-devis': typeof AuthenticatedMesDevisRoute
  '/admin/devis': typeof AdminDevisRoute
  '/admin/produits': typeof AdminProduitsRoute
  '/admin/utilisateurs': typeof AdminUtilisateursRoute
  '/produits/$id': typeof ProduitsIdRoute
  '/admin/': typeof AdminIndexRoute
  '/produits/': typeof ProduitsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/mes-devis'
    | '/admin/devis'
    | '/admin/produits'
    | '/admin/utilisateurs'
    | '/produits/$id'
    | '/admin/'
    | '/produits/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/mes-devis'
    | '/admin/devis'
    | '/admin/produits'
    | '/admin/utilisateurs'
    | '/produits/$id'
    | '/admin'
    | '/produits'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/admin'
    | '/auth'
    | '/_authenticated/mes-devis'
    | '/admin/devis'
    | '/admin/produits'
    | '/admin/utilisateurs'
    | '/produits/$id'
    | '/admin/'
    | '/produits/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ProduitsIdRoute: typeof ProduitsIdRoute
  ProduitsIndexRoute: typeof ProduitsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/mes-devis': {
      id: '/_authenticated/mes-devis'
      path: '/mes-devis'
      fullPath: '/mes-devis'
      preLoaderRoute: typeof AuthenticatedMesDevisRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/devis': {
      id: '/admin/devis'
      path: '/devis'
      fullPath: '/admin/devis'
      preLoaderRoute: typeof AdminDevisRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/produits': {
      id: '/admin/produits'
      path: '/produits'
      fullPath: '/admin/produits'
      preLoaderRoute: typeof AdminProduitsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/utilisateurs': {
      id: '/admin/utilisateurs'
      path: '/utilisateurs'
      fullPath: '/admin/utilisateurs'
      preLoaderRoute: typeof AdminUtilisateursRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/produits/': {
      id: '/produits/'
      path: '/produits'
      fullPath: '/produits/'
      preLoaderRoute: typeof ProduitsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produits/$id': {
      id: '/produits/$id'
      path: '/produits/$id'
      fullPath: '/produits/$id'
      preLoaderRoute: typeof ProduitsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedMesDevisRoute: typeof AuthenticatedMesDevisRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedMesDevisRoute: AuthenticatedMesDevisRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AdminRouteRouteChildren {
  AdminDevisRoute: typeof AdminDevisRoute
  AdminProduitsRoute: typeof AdminProduitsRoute
  AdminUtilisateursRoute: typeof AdminUtilisateursRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminDevisRoute: AdminDevisRoute,
  AdminProduitsRoute: AdminProduitsRoute,
  AdminUtilisateursRoute: AdminUtilisateursRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ProduitsIdRoute: ProduitsIdRoute,
  ProduitsIndexRoute: ProduitsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
